services:
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        container_name: etoile-frontend
        working_dir: /workspace
        volumes:
            - ./frontend:/workspace
            - node_modules:/workspace/node_modules
        ports:
            - "5173:5173"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        restart: unless-stopped
        stdin_open: true
        tty: true
        command: ["bash", "/workspace/init.sh"]
    
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: etoile-backend
        working_dir: /workspace
        volumes:
            - ./backend:/workspace
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - db
        restart: unless-stopped
        stdin_open: true
        tty: true
        command: ["ash", "/workspace/init.sh"]

    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: etoitoitest
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    node_modules:
    postgres_data: